# Generated by Django 5.1.3 on 2024-11-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
    ]
